# use the latest ubuntu environment (18.04) available on travis
dist: bionic

language: go

# Only clone the most recent commit.
git:
  depth: 1

before_install:
  - sudo apt-get -y install libwebkit2gtk-4.0-dev
  - nvm install stable
  - go get -u github.com/go-bindata/go-bindata/...

install:
  - make compile-assets
  - env GO111MODULE=on go get
  - npm install
  

# Don't email me the results of the test runs.
notifications:
  email: false

# script always runs to completion (set +e). If we have linter issues AND a
# failing test, we want to see both. Configure golangci-lint with a
# .golangci.yml file at the top level of your repo.
script:
  - make js-lint
  - env GO111MODULE=on make test
  - env GO111MODULE=on make build-dev