// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:string):Promise<string>;

export function DeleteConnection(arg1:string):Promise<string>;

export function GetConnections():Promise<string>;

export function GetDatabases():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function RunQuery(arg1:string,arg2:string):Promise<string>;

export function StoreConnections(arg1:string):Promise<string>;
